package com.sky.mybatisgenerator.dao;

import lombok.Builder;
import lombok.ToString;

import java.util.Date;

@Builder
@ToString
public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ID
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.EMAIL
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.PASSWORD
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.NAME
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.REGDATE
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    private Date regdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ID
     *
     * @return the value of member.ID
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ID
     *
     * @param id the value for member.ID
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.EMAIL
     *
     * @return the value of member.EMAIL
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.EMAIL
     *
     * @param email the value for member.EMAIL
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.PASSWORD
     *
     * @return the value of member.PASSWORD
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.PASSWORD
     *
     * @param password the value for member.PASSWORD
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.NAME
     *
     * @return the value of member.NAME
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.NAME
     *
     * @param name the value for member.NAME
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.REGDATE
     *
     * @return the value of member.REGDATE
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.REGDATE
     *
     * @param regdate the value for member.REGDATE
     *
     * @mbg.generated Thu May 16 15:25:23 KST 2024
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
}