package com.sky.mybatisdynamic.dao.scott;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    private Short deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.DEPT.LOC
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.DEPTNO
     *
     * @return the value of SCOTT.DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.DEPTNO
     *
     * @param deptno the value for SCOTT.DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.DNAME
     *
     * @return the value of SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.DNAME
     *
     * @param dname the value for SCOTT.DEPT.DNAME
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.DEPT.LOC
     *
     * @return the value of SCOTT.DEPT.LOC
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.DEPT.LOC
     *
     * @param loc the value for SCOTT.DEPT.LOC
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    public void setLoc(String loc) {
        this.loc = loc == null ? null : loc.trim();
    }
}