package com.sky.mybatisdynamic.mapper.scott;

import com.sky.mybatisdynamic.dao.scott.Dept;
import com.sky.mybatisdynamic.dao.scott.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int deleteByPrimaryKey(Short deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    Dept selectByPrimaryKey(Short deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.DEPT
     *
     * @mbg.generated Thu May 16 17:22:38 KST 2024
     */
    int updateByPrimaryKey(Dept record);
}