server:
  port: 8083

spring:
  application:
    name: msa-service-coffee-status
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: 'msa-architecture-server-config'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#Config Server      
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: msa-architecture-config-server

#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/ #, http://localhost:9092/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id:

logging:
  path: logs
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.hoony.msa.status.system: DEBUG
    com.hoony.msa.status.springboot: DEBUG